// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActZFAJtkK2qqygu2dIEAX6rN2cS-lrug',
    appId: '1:633466708065:web:6dd4d6804cee6178704a20',
    messagingSenderId: '633466708065',
    projectId: 'precios-cotizawebbuilder',
    authDomain: 'precios-cotizawebbuilder.firebaseapp.com',
    databaseURL: 'https://precios-cotizawebbuilder-default-rtdb.firebaseio.com',
    storageBucket: 'precios-cotizawebbuilder.appspot.com',
    measurementId: 'G-53XKXP0FLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22zYJTI6igp6eU7fk4KWDTctPCQpSnVM',
    appId: '1:633466708065:android:85ae0c519b193eab704a20',
    messagingSenderId: '633466708065',
    projectId: 'precios-cotizawebbuilder',
    databaseURL: 'https://precios-cotizawebbuilder-default-rtdb.firebaseio.com',
    storageBucket: 'precios-cotizawebbuilder.appspot.com',
  );

}